server:
  port: 8013
spring:
  application:
    name: service13-sqlserver


  datasource:
    username: root
    password: 123456
    url: jdbc:sqlserver://localhost:1433;sslProtocol=TLSv1.2;DatabaseName=db_user
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  mapper-locations: classpath:com/krest/sqlserver/mapper/*.xml
  type-aliases-package: com.krest.sqlserver.entity
