#用户中心服务端口
server:
  port: 8023
#数据源配置

#dubbo配置
dubbo:
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.krest.dubbo
  protocol:
    port: 20880
    name: dubbo
  registry:
    #zookeeper注册中心地址
    address: zookeeper://192.168.0.107:2181